myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
				path('', views.cart_detail, name='cart_detail'),
				path('add/<int:product_id>/', views.cart_add, name='cart_add'),
				path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
				]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    url(r'^search/', include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/search/urls.py
from django.urls import path
 
from .views import SearchView
 
urlpatterns = [
    path('search/', SearchView.as_view(), name='search_results'),
]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/search/models.py
from django.db import models

# Create your models here.

myshop/shop/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name




class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,)

    def __str__(self):
        return self.comment


    def get_absolute_url(self):
        return reverse('product_list')

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False,
		initial=False,
		widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product,
			quantity=cd['quantity'],
			update_quantity=cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')


def cart_detail(request):
	cart = Cart(request)
	return render(request, 'cart/detail.html', {'cart': cart})

myshop/search/views.py
from django.views.generic import  ListView
from shop.models import Product
from django.db.models import Q
class SearchView(ListView):
    model = Product
    template_name = 'search.html'
 
    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
            Q(name__icontains=query) | Q(image__icontains=query)
        )
        return object_list

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


# from django.db.models import Q




def product_list(request, category_slug=None):
    # search_query = request.GET.get('search','')
    # if search_query:
    #     products = Product.objects.filter(Q(name__icontains=search_query))
    # else:
    #     products = Product.objects.all()       
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
  product = get_object_or_404(Product, id=id, slug=slug, available=True)
  cart_product_form = CartAddProductForm()
  return render(request, 'product/detail.html',{'product': product,
    'cart_product_form': cart_product_form,})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Your shopping cart{% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
<thead>
<tr>
<th>Image</th>
<th>Product</th>
<th>Quantity</th>
<th>Remove</th>
<th>Unit price</th>
<th>Price</th>
</tr>
</thead>
<tbody>
{% for item in cart %}
{% with product=item.product %}
<tr>
<td>
<a href="{{ product.get_absolute_url }}">
<img src="{% if product.image %}{{ product.image.url }}
{% else %}{% static 'img/no_image.png' %}{% endif %}">
</a>
</td>
<td>{{ product.name }}</td>
<td>{{ item.quantity }}</td>
<td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
<td class="num">${{ item.price }}</td>
<td class="num">${{ item.total_price }}</td>
</tr>
{% endwith %}
{% endfor %}
<tr class="total">
<td>Total</td>
<td colspan="4"></td>
<td class="num">${{ cart.get_total_price }}</td>
</tr>
</tbody>
</table>
<p class="text-right">
<a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
<a href="#" class="button">Checkout</a>
</p>
{% endblock %}

myshop/search/templates/search.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
  {% for product in object_list %}
    <div>
        <img src="{% if product.image %}{{ product.image.url }}
            {% else %}{% static 'img/no_image.png' %}{% endif %}">
        <h1>{{ product.name }}</h1> <h2>
        <a href="{{ product.category.get_absolute_url }}">{{product.category }}</a> </h2>
        <p class="price">${{ product.price }}</p>
    </div>
  {% endfor %}
{% endblock %}

myshop/shop/templates/product/detail.html
{% extends "shop/base.html" %}
{% load static %}



{% block title %}
{{ product.name }}
{% endblock %}



{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}
        {% else %}{% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ product.name }}</h1> <h2>
    <a href="{{ product.category.get_absolute_url }}">{{product.category }}</a> </h2>
    <p class="price">${{ product.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
    </form>
    {{ product.description|linebreaks }} 
</div>
{% endblock %}

myshop/shop/templates/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected"{% endif %}> <a href="{% url "shop:product_list" %}">All</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.img' %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a> <br>
        ${{ product.price }}
    </div>
    {% endfor %}
</div>
{% endblock %}

myshop/shop/templates/shop/base.html
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
	<div id="header">
    	<a href="/" class="logo">My shop</a>
	</div>
<div class='social'>
    <ul>
        <li class="google">
            <a href="{% url 'social:begin' 'google-oauth2' %}">
            Login with Google
            </a>
        </li>
        <li class="vk">
            <a href="{% url 'social:begin' 'vk-oauth2' %}">Login with VK</a>
        </li>
            <li class="facebook"><a href="{% url 'social:begin' 'facebook' %}">
            Signin with Facebook</a></li>
    </ul>
</div>
<form action="{% url 'search_results' %}" method="get">
  <input name="q" type="text" placeholder="Search...">
</form>
	<div id="subheader">
    	<div class="cart">
            <a href="{% url 'cart:cart_detail' %}">Cart</a>
        </div> 
	</div>
	<div id="content">
    	{% block content %}
    	{% endblock %}
	</div>
</body>
</html>